select 
 '(',
 Dinner_ID, ',',
 '"' + trim(Dinner_Name) + '"', ',',
 '"' + trim(Url) + '"', ',',
 Portions , ',',
 '"' + trim(Tags) + '"', ',',
 '"' + trim(PicUrl) + '"',
 '),'
 from Dinners;


SET IDENTITY_INSERT Dinners ON;

insert into Dinners(ID, Name, PicUrl, Portions, Tags, Url) values 
(	1	,	'Gulrotsuppe'	,	'http://trinesmatblogg.no/2015/01/20/gulrotsuppe-med-appelsin-og-ingefaer/'	,	2	,	'sunt, suppe, enkelt, lett, spicy'	,	'http://i2.wp.com/trinesmatblogg.no/wp-content/uploads/2015/01/IMG_3137.jpg?w=873'	),
(	2	,	'Fiskekaker med couscous'	,	'http://www.smabarnsforeldre.no/couscous-salat-fantastisk-tilbehor-til-fiskekaker/'	,	2	,	'Sunt, fisk, enkelt'	,	'http://www.smabarnsforeldre.no/wp-content/uploads/2015/08/11373588_1641628942787223_1914020410_n.jpg'	),
(	3	,	'Lompepizza med pesto'	,	'http://www.lindastuhaug.no/2016/10/24/lompepizza-med-pesto/'	,	2	,	'Sunt, vegetar, enkelt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Lompepizza_med_pesto.jpg'	),
(	4	,	'Kyllingwrap'	,	''	,	4	,	'Enkelt, godt, raskt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kyllingwrap.jpg'	),
(	5	,	'Cowboygryte'	,	''	,	4	,	'Spicy, enkelt, todagers'	,	'https://middagsappbilder.blob.core.windows.net/middag/Cowboygryte.jpg'	),
(	6	,	'Middagspai med søtpotetbunn'	,	'http://lindastuhaug.blogg.no/1402586164_pai.html'	,	4	,	'Linda, Sunt, søtpotet, hverdagsmat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Søtpotetpai.jpg'	),
(	7	,	'Kylling med mango chutney'	,	''	,	3	,	'Spicy, godt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kylling_med_mango_chutney.jpg'	),
(	11	,	'Torsk med søtpotetmos'	,	'http://www.lindastuhaug.no/2017/01/03/torsk-sotpotetmos-bacon-erter/'	,	2	,	'Sunt, fisk, enkelt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Torsk_med_søtpotetmos.jpg'	),
(	12	,	'Spaghetti Bolognese'	,	''	,	4	,	'Godt, italiensk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Spaghetti_Bolognese.jpg'	),
(	14	,	'Lasagne'	,	''	,	2	,	'Helg, namnam, date, italiensk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Lasagne.jpg'	),
(	15	,	'Kreolsk laks med søtpotetpure'	,	''	,	2	,	'Sunt, enkelt, fisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kreolsk_laks_med_søtpotetpure.jpg'	),
(	16	,	'Blomkålsuppe'	,	'http://trinesmatblogg.no/2013/08/08/blomkalsuppe-med-purre-og-sprostekt-bacon/'	,	3	,	'suppe, godt, lunsj'	,	'https://middagsappbilder.blob.core.windows.net/middag/Blomkålsuppe.jpg'	),
(	18	,	'Spaghetti med reker og chili'	,	''	,	2	,	'Spicy, enkelt, sjømat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Spaghetti_med_reker_og_chili.jpg'	),
(	22	,	'Indrefilet av svin med søtpotetpuré'	,	''	,	2	,	'Enkelt'	,	''	),
(	25	,	'Enchiladas'	,	''	,	4	,	'Helg, namnam, meksikansk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Enchiladas.jpg'	),
(	33	,	'Hamburger'	,	''	,	2	,	'Helg, namnam, enkelt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Hamburger.jpg'	),
(	34	,	'Pulled pork sandwhich'	,	''	,	4	,	'Enkelt, namnam'	,	'https://middagsappbilder.blob.core.windows.net/middag/Pulled_pork_sandwhich.jpg'	),
(	35	,	'Grillet kylling med coleslaw'	,	''	,	4	,	'Enkelt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Grilled_kylling_med_coleslaw.jpg'	),
(	36	,	'Donkatsu'	,	''	,	2	,	'Japansk, godt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Donkatsu.jpg'	),
(	38	,	'Søtpotet scones'	,	'http://www.lindastuhaug.no/2015/03/27/sotpotet-scones/'	,	4	,	'scone, brød, mellommåltid, Linda, bakevarer'	,	'https://middagsappbilder.blob.core.windows.net/middag/Søtpotet_scones.jpg'	),
(	39	,	'Søtpotet nachos'	,	'http://www.lindastuhaug.no/2015/11/07/sotpotet-nachos/'	,	3	,	'søtpotet, nachos, fredag, Linda, meksikansk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Søtpotet_nachos.jpg'	),
(	40	,	'Quesedilla med kylling og pesto'	,	'http://www.lindastuhaug.no/2016/03/10/quesedilla-med-kylling-og-pesto/'	,	2	,	'Linda, freda, quesedilla, meksikansk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Quesedilla_med_kylling_og_pesto.jpg%3Fquality=90'	),
(	41	,	'Lakselasagne med spinat'	,	'http://www.lindastuhaug.no/2016/06/09/lakselasagne/'	,	3	,	'Linda, fisk, sunn, laks'	,	'https://middagsappbilder.blob.core.windows.net/middag/Lakselasagne_med_spinat.jpg%3Fquality=90'	),
(	42	,	'søtpotetmosgrateng'	,	'http://www.lindastuhaug.no/2014/11/07/smakfull-sotpotetmosgrateng/'	,	4	,	'sunn, Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/søtpotetmosgrateng.jpg%3Fw=1010&quality=90'	),
(	45	,	'Søtpotet Croque monsieur'	,	'http://m.blog.naver.com/hobaragi201/220860949132'	,	2	,	'enkel, lett'	,	'https://middagsappbilder.blob.core.windows.net/middag/Søtpotet_Croque_monsieur.jpg'	),
(	46	,	'Pasta All’Arrabbiata'	,	'http://trinesmatblogg.no/2014/03/18/pasta-allarrabbiata/'	,	4	,	'italiensk, trine, vegetar'	,	'https://middagsappbilder.blob.core.windows.net/middag/PASTA_ALL’_ARRABBIATA.jpg%3Fw=640'	),
(	47	,	'Kylling og paprika med hot mangosaus'	,	'http://trinesmatblogg.no/2015/08/25/kylling-og-paprika-med-hot-mangosaus/'	,	4	,	'indisk, sunt, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/KYLLING_OG_PAPRIKA_MED_HOT_MANGOSAUS.jpg%3Fw=800'	),
(	48	,	'Spicy nudelsalat med laks'	,	'http://trinesmatblogg.no/2016/04/12/spicy-nudelsalat-med-laks/'	,	4	,	'trine, fisk, sunt'	,	'https://middagsappbilder.blob.core.windows.net/middag/SPICY_NUDELSALAT_MED_LAKS.jpg%3Fw=800'	),
(	49	,	'huevo a la flamenca'	,	'http://javirecetas.hola.com/huevos-a-la-flamenca/'	,	2	,	'Sausen, spicy'	,	'https://middagsappbilder.blob.core.windows.net/middag/huevo_a_la_flamenca.jpg'	),
(	50	,	'Tomatsuppe med tortellini og pølse'	,	'http://trinesmatblogg.no/2015/10/05/tomatsuppe-med-tortellini-og-polse/'	,	4	,	'usunt, godt, nam, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/TOMATSUPPE_MED_TORTELLINI_OG_PØLSE.jpg%3Fw=800'	),
(	51	,	'Kyllingnuggets med dip og potetstaver'	,	'http://trinesmatblogg.no/2014/10/16/kyllingnuggets-med-dip-og-potetstaver/'	,	2	,	'trine, godt'	,	'https://middagsappbilder.blob.core.windows.net/middag/KYLLINGNUGGETS_MED_DIP_OG_POTETSTAVER.jpg%3Fw=800'	),
(	52	,	'Kyllingsuppe med nudler, paprika og chili'	,	'http://trinesmatblogg.no/2014/10/07/kyllingsuppe-med-nudler-paprika-og-chili/'	,	4	,	'kylling, asiatisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/KYLLINGSUPPE_MED_NUDLER,_PAPRIKA_OG_CHILI.jpg%3Fw=800'	),
(	53	,	'Thai fiskesuppe'	,	'http://trinesmatblogg.no/2014/09/17/signaturretten-arets-matblogger-thaisuppe/'	,	4	,	'fisk, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/THAI_fiskesuppe.jpg%3Fw=563'	),
(	54	,	'Hummus'	,	''	,	4	,	'side'	,	'http://assets.simplyrecipes.com/wp-content/uploads/2006/04/hummus-horiz-a-1200.jpg'	),
(	55	,	'Tomatsuppe'	,	'http://trinesmatblogg.no/2013/12/10/hjemmelaget-tomatsuppe-2/'	,	4	,	'trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/TOMATSUPPE.jpg%3Fw=800'	),
(	56	,	'Banankake i kopp'	,	'http://www.lindastuhaug.no/2017/03/23/rask-og-enkel-banankake-kopp/'	,	2	,	'sunt, dessert, linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/banankake_i_kopp.jpg%3Fw=938&quality=90'	),
(	57	,	'Spicy kyllingsuppe med mais og nachochips'	,	'http://trinesmatblogg.no/2012/06/21/spicy-kyllingsuppe-med-mais-og-nachochips/'	,	2	,	'meksikansk, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Spicy_kyllingsuppe_med_mais_og_nachochips.jpg%3Fw=800'	),
(	58	,	'Heimelaga moussaka med søtpotet'	,	'http://www.lindastuhaug.no/2014/08/13/heimelaga-moussaka-med-sotpotet/'	,	5	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Heimelaga_moussaka_med_søtpotet.jpg%3Fw=1010&quality=90'	),
(	60	,	'the world’s easiest cookies'	,	'http://www.carolinebergeriksen.no/2017/04/03/worlds-easiest-cookies/'	,	12	,	'cookies, kjeks, sunt, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/the_world’s_easiest_cookies.jpg'	),
(	61	,	'bliss balls med bringebær'	,	'http://www.carolinebergeriksen.no/2016/03/11/fredagssnacksen-bliss-balls-med-bringebaer/'	,	1	,	'sunt, dessert, snacks'	,	'https://middagsappbilder.blob.core.windows.net/middag/bliss_balls_med_bringebær.jpg'	),
(	62	,	'hvite trøfler'	,	'http://www.carolinebergeriksen.no/2016/02/05/fredagssnacksen-sukkerfrie-hvite-trofler/'	,	1	,	'sunt, dessert, snack'	,	'https://middagsappbilder.blob.core.windows.net/middag/hvite_trøfler.jpg'	),
(	63	,	'Gulrotcupcakes med mandarinkrem'	,	'http://www.detsoteliv.no/oppskrift/gulrotcupcakes-med-mandarinkrem'	,	24	,	'dessert, usunt, godt, fest'	,	'https://middagsappbilder.blob.core.windows.net/middag/Gulrotcupcakes_med_mandarinkrem.jpg'	),
(	64	,	'Havrekjeks med eple og kanel'	,	'http://www.lindastuhaug.no/2015/10/07/havrekjeks-med-eple-og-kanel/'	,	5	,	'sunt, dessert, kjeks, snacks'	,	'https://eu-central-1.tchyn.io/unitedbloggers-production/uploads/sites/185/2015/10/IMG_1826.jpg'	),
(	65	,	'Meat Pie Muffins'	,	'http://www.foodtolove.com.au/recipes/meat-pie-muffins-12330'	,	2	,	'Snack, lunsj, enkelt, tapas'	,	'https://middagsappbilder.blob.core.windows.net/middag/Meat_Pie_Muffins.png'	),
(	66	,	'Lasagna med aubergine'	,	'http://www.carolinebergeriksen.no/2011/01/05/oppskrift-lasagne/'	,	6	,	'Sunt, glutenfri'	,	'https://eu-central-1.tchyn.io/unitedbloggers-production/uploads/sites/197/2011/01/DSC08248.jpg?resize=535,356&quality=90'	),
(	67	,	'Sitronkake'	,	'http://www.detsoteliv.no/oppskrift/sitronkake-i-langpanne'	,	6	,	'Kake, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Sitronkake.jpg'	),
(	68	,	'ELTEFRIE RUGRUNDSTYKKER MED FRØ'	,	'http://trinesmatblogg.no/2014/12/17/eltefrie-rugrundstykker-med-fro/'	,	12	,	'Rundstykker, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/ELTEFRIE_RUGRUNDSTYKKER_MED_FRØ.jpg'	),
(	69	,	'Glutenfrie rundstykker med cottage cheese og havre'	,	'http://www.godt.no/#!/oppskrift/7276/glutenfrie-rundstykker-med-cottage-cheese-og-havre'	,	12	,	'Sunt, rundstykker'	,	'https://middagsappbilder.blob.core.windows.net/middag/glutenfrie_rundtstykker_med_cottage_cheese.jpg'	),
(	70	,	'FISKEPINNER MED RÅKOSTSALAT OG CHILIMAJONES'	,	'http://trinesmatblogg.no/2015/08/27/fiskepinner-med-rakostsalat-og-chilimajones/'	,	4	,	'Trine, fisk'	,	'http://i0.wp.com/trinesmatblogg.no/wp-content/uploads/2015/08/IMG_6861.jpg'	),
(	74	,	'Lemonies'	,	'http://www.detsoteliv.no/oppskrift/lemonies'	,	10	,	'Dessert, kake, namnam'	,	'https://middagsappbilder.blob.core.windows.net/middag/Lemonies.jpg%3Fitok=ydyF53AQ'	),
(	75	,	'Kylling med parmaskinke og risotto'	,	'https://www.aperitif.no/oppskrifter/oppskrift/kylling-med-parmaskinke-og-risotto/63050'	,	4	,	'Godt, helg, italiensk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kylling_med_parmaskinke_og_risotto.jpg'	),
(	76	,	'Potet- og purresuppe med sprøstekt bacon'	,	'http://trinesmatblogg.no/2012/04/30/potet-og-purresuppe-med-sprostekt-bacon/'	,	4	,	'Trine, suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Potet-_og_purresuppe_med_sprøstekt_bacon.jpg'	),
(	77	,	'Ovnsstekte kyllinglår med rosmarin og sitron'	,	'http://www.godt.no/#!/oppskrift/3605/ovnsstekte-kyllinglaar-med-rosmarin-og-sitron'	,	4	,	''	,	'https://middagsappbilder.blob.core.windows.net/middag/ovnstekte_kyllingl%C3%A5r.jpg'	),
(	78	,	'Tyrkisk salat med svart ris'	,	'http://frutimian.no/2013/04/04/tyrkisk-salat-med-svart-ris/'	,	4	,	'salat, fru timian'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tyrkisk_salat_med_svart_ris.jpg'	),
(	79	,	'pastasalat med svinefilet, avokado og tomater'	,	'https://frutimian.no/2017/06/21/pastasalat-med-svinefilet/'	,	4	,	'salat, pasta, fru timian'	,	'https://middagsappbilder.blob.core.windows.net/middag/pastasalat_med_svinefilet,_avokado_og_tomater.jpg'	),
(	80	,	'Quinoasalat med tatziki'	,	'http://www.lindastuhaug.no/2017/07/03/fargerik-quinoasalat-med-tatziki/'	,	4	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Quinoasalat_med_tatziki.jpg'	),
(	81	,	'Pytt i panne med bønner'	,	'http://www.lindastuhaug.no/2017/05/08/pytt-panne-med-bonner/'	,	2	,	''	,	'https://middagsappbilder.blob.core.windows.net/middag/Pytt_i_panne_med_bønner.jpg'	),
(	82	,	'Søtpotetsuppe med kokosmelk'	,	'http://www.lindastuhaug.no/2016/10/31/sotpotetsuppe-med-kokosmelk/'	,	2	,	'suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Søtpotetsuppe_med_kokosmelk.jpg'	),
(	87	,	'TORSK MED BALSAMICO'	,	'http://trinesmatblogg.no/2017/02/19/pannestekt-torsk-med-balsamicovinaigrette-og-soltorkede-cherrytomater/'	,	4	,	'fisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/TORSK_MED_BALSAMICO.jpg'	),
(	88	,	'SPAGETTI MED KAVIAR ELLER ROGN'	,	'http://maaltid.no/oppskrifter/spagetti-med-kaviar-eller-rogn'	,	4	,	'spagetti'	,	'https://middagsappbilder.blob.core.windows.net/middag/SPAGETTI_MED_KAVIAR_ELLER_ROGN.jpg'	),
(	89	,	'Kylling med mango og peanøttdip'	,	'http://sirifossing.blogg.no/1492631409_hne_med_mango_og_peanttdip.html'	,	4	,	'siri'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kylling_med_mango_og_peanøttdip.jpg'	),
(	90	,	'Ørret Philly'	,	'http://sirifossing.blogg.no/1426594131_rret_philly.html'	,	4	,	'siri'	,	'https://middagsappbilder.blob.core.windows.net/middag/Ørret_Philly.jpg'	),
(	91	,	'Shredded Beef for Tacos or Burritos'	,	'http://www.food.com/recipe/shredded-beef-for-tacos-or-burritos-228102?mode=metric&st=true&scaleto=5'	,	4	,	'Helg, slowcook'	,	'https://middagsappbilder.blob.core.windows.net/middag/Shredded_Beef_for_Tacos_or_Burritos.jpg'	),
(	92	,	'Thailandsk kyllingform'	,	'http://www.lindastuhaug.no/2014/10/28/thailandsk-kyllingform/'	,	4	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Thailandsk_kyllingform.jpg'	),
(	93	,	'Pastasalat'	,	''	,	4	,	'Sausen'	,	''	),
(	94	,	'Tomat- og mozzarellasalat med syltet rødløk'	,	'http://trinesmatblogg.no/2012/11/15/tomat-og-mozzarellasalat-med-syltet-rodlok/'	,	4	,	'Forrett'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tomat-_og_mozzarellasalat_med_syltet_rødløk.jpg%3Fw=771'	),
(	95	,	'Pannestekt breiflabb'	,	'http://trinesmatblogg.no/2012/11/19/pannestekt-breiflabb-med-tomatolje-spinat-og-ovnsbakt-gulloye/'	,	4	,	'Fisk, Lotte'	,	'https://middagsappbilder.blob.core.windows.net/middag/Pannestekt_breiflabb.jpg%3Fw=800'	),
(	96	,	'Panna cotta med appelsinsaus'	,	'http://trinesmatblogg.no/2015/12/12/julens-panna-cotta-med-appelsinsaus/'	,	4	,	'Dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Panna_cotta_med_appelsinsaus.jpg%3Fw=800'	),
(	97	,	'RAGÙ ALLA BOLOGNESE'	,	'http://trinesmatblogg.no/2013/09/03/ragu-alla-bolognese/'	,	10	,	'Trine, kjøttsaus'	,	'https://middagsappbilder.blob.core.windows.net/middag/RAGÙ_ALLA_BOLOGNESE.jpg'	),
(	98	,	'BOLOGNESE MED POTET- OG PERSILLEROTLOKK'	,	'http://trinesmatblogg.no/2013/09/16/bolognese-med-potetlokk/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/BOLOGNESE_MED_POTET-_OG_PERSILLEROTLOKK.jpg'	),
(	99	,	'vårruller'	,	'http://www.lindastuhaug.no/2015/04/21/enkle-og-smakfulle-varruller/'	,	2	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/vårruller.jpg'	),
(	100	,	'Sukkerfri, enkel snickerskake'	,	'http://www.lindastuhaug.no/2014/04/19/oppskrift-sukkerfri-enkel-snickerskake/'	,	4	,	'Linda, dessert, snack'	,	'https://middagsappbilder.blob.core.windows.net/middag/Sukkerfri,_enkel_snickerskake.jpg'	),
(	101	,	'Cæsarsalat'	,	'http://trinesmatblogg.no/2010/07/01/cæsarsalat/'	,	2	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Cesærsalar_.jpg'	),
(	102	,	'Grønn kyllingcurry med paprika og squash'	,	'http://trinesmatblogg.no/2016/05/24/gronn-kyllingcurry-med-paprika-og-squash/'	,	4	,	'Spicy, thai, suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Grønn_kyllingcurry_med_paprika_og_squash.jpg%3Fw=669'	),
(	103	,	'Bouillabaisse - Fransk fiskesuppe'	,	'http://trinesmatblogg.no/2014/09/04/bouillabaisse-fransk-fiskesuppe/'	,	4	,	'Fisk, suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Bouillabaisse_-_Fransk_fiskesuppe.jpg%3Fw=411'	),
(	104	,	'Gratinert blomkål med pesto'	,	'http://www.godt.no/#!/oppskrift/8162/gratinert-blomkaal-med-pesto'	,	4	,	'blomkål'	,	'https://middagsappbilder.blob.core.windows.net/middag/gratinert_blomkal_med_pesto.jpg'	),
(	105	,	'Tunfisk salat'	,	'http://www.lindastuhaug.no/2016/01/19/krema-tunfisksalat-som-palegg-eller-fargerik-lunsjsalat/'	,	2	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tunfisk_salat_.jpg'	),
(	106	,	'Fårikål'	,	'http://www.crockpot.no/oppskrift/far-i-kal/'	,	2	,	'Norsk, lam'	,	'https://middagsappbilder.blob.core.windows.net/middag/Fårikål.jpg'	),
(	107	,	'Tacosuppe'	,	'http://www.lindastuhaug.no/2016/05/20/tacosuppe/'	,	4	,	'Linda, suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tacosuppe.jpg'	),
(	108	,	'Spinatpai med soltørket tomat og feta'	,	'http://trinesmatblogg.no/2011/01/26/spinatpai-med-solt%C3%B8rket-tomat-og-feta/'	,	3	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Spinatpai_med_soltørket_tomat_og_feta.jpg'	),
(	109	,	'Sunne og enkle vafler med cottage cheese'	,	'http://www.lindastuhaug.no/2017/10/18/sunne-og-enkle-vafler-med-cottage-cheese/'	,	3	,	'Linda, vafler'	,	'https://middagsappbilder.blob.core.windows.net/middag/Sunne_og_enkle_vafler_med_cottage_cheese.jpg'	),
(	110	,	'SØTPOTET FAJITAS'	,	'http://dedication.blogg.no/1508420846_stpotet_fajitas.html'	,	2	,	'meksikansk'	,	'https://middagsappbilder.blob.core.windows.net/middag/SØTPOTET_FAJITAS.jpg'	),
(	111	,	'Sukkerfri kvikk lunsj'	,	'http://www.lindastuhaug.no/2017/04/05/sukkerfri-kvikk-lunsj/'	,	2	,	'linda, snack'	,	'https://middagsappbilder.blob.core.windows.net/middag/Sukkerfri_kvikk_lunsj.jpg'	),
(	112	,	'Glutenfri nanbrød'	,	'https://bubblesinlife.com/2013/03/03/glutenfrie-nanbrod-med-koriander/'	,	4	,	'Indisk, glutenfri'	,	'https://middagsappbilder.blob.core.windows.net/middag/Glutenfri_nanbrød.jpg'	),
(	113	,	'Indisk Masala'	,	''	,	4	,	'Indisk, namnam'	,	'https://middagsappbilder.blob.core.windows.net/middag/Indisk_Masala.jpg'	),
(	114	,	'Mangolassi'	,	'https://www.jamieoliver.com/recipes/fruit-recipes/mango-lassi/'	,	4	,	'Indisk, drikke'	,	'https://middagsappbilder.blob.core.windows.net/middag/Mangolassi.jpg'	),
(	115	,	'Fransk lammegryte med ovnstekte poteter'	,	'http://trinesmatblogg.no/2010/10/19/fransk-lammegryte-med-ovnstekte-poteter/'	,	4	,	'trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Fransk_lammegryte_med_ovnstekte_poteter.jpg'	),
(	116	,	'Kålrabistappe'	,	'http://trinesmatblogg.no/2011/12/27/juleskinke-med-kalrotstappe-og-sennepsaus/'	,	4	,	'Jul'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kålrabistappe.jpg%3Fresize=400%252C267'	),
(	117	,	'Frisk quinoasalat med halloumi'	,	'http://www.lindastuhaug.no/2017/11/27/frisk-quinoasalat-med-halloumi/'	,	2	,	'linda, salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Frisk_quinoasalat_med_halloumi.jpg'	),
(	118	,	'FALAFEL I PITABRØD'	,	'http://kvardagsmat.no/2016/04/11/falafel-i-pitabrod/'	,	4	,	'falafel'	,	'https://middagsappbilder.blob.core.windows.net/middag/FALAFEL_I_PITABRØD.jpg'	),
(	119	,	'Seige pistasje trøfler'	,	'http://www.lindastuhaug.no/2016/04/07/seige-pistasje-trofler/'	,	10	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Seige_pistasje_trøfler.jpg'	),
(	120	,	'Sukkerfri, sprø havreflarn'	,	'http://www.lindastuhaug.no/2017/12/04/sukkerfri-spro-havreflarn/'	,	25	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Sukkerfri,_sprø_havreflarn.jpg'	),
(	121	,	'Peanøtt-trøfler med sjokoladetrekk'	,	'http://www.lindastuhaug.no/2017/08/22/peanott-trofler-med-sjokoladetrekk/'	,	20	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Peanøtt-trøfler_med_sjokoladetrekk.jpg'	),
(	122	,	'Kylling i karri påleggsalat'	,	'http://www.lindastuhaug.no/2015/04/28/kylling-i-karri-paleggsalat/'	,	2	,	'linda, pålegg'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kylling_i_karri_påleggsalat.jpg'	),
(	123	,	'Flyvende Jacob'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/kylling-og-fjarkre/flyvende-jacob'	,	3	,	'Tine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Flyvende_Jacob.jpg'	),
(	124	,	'Kyllingwok med krema, enkel woksaus'	,	'http://www.lindastuhaug.no/2016/10/04/kyllingwok-krema-enkel-woksaus/'	,	3	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kyllingwok_med_krema,_enkel_woksaus.jpg'	),
(	125	,	'WOK MED BIFF OG APPELSINSAUS'	,	'https://trinesmatblogg.no/recipe/wok-med-biff-og-appelsinsaus/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/WOK_MED_BIFF_OG_APPELSINSAUS.jpg'	),
(	126	,	'SPAGETTI CARBONARA'	,	'https://trinesmatblogg.no/recipe/spagetti-carbonara-video/'	,	4	,	'trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/SPAGETTI_CARBONARA.jpg'	),
(	127	,	'FINNBIFF MED BACON, ROSENKÅL OG SELLERIROTMOS'	,	'https://trinesmatblogg.no/recipe/finnbiff-med-bacon-rosenkal-og-sellerirotmos/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/FINNBIFF_MED_BACON,_ROSENKÅL_OG_SELLERIROTMOS.jpg'	),
(	128	,	'taco lasagne'	,	'http://www.lindastuhaug.no/2017/04/07/sunn-og-enkel-tacolasagne/'	,	3	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/taco_lasagne.jpg'	),
(	129	,	'Vaffelomelett med bacon'	,	'http://www.lindastuhaug.no/2017/04/19/vaffelomelett-perfekt-matpakken/'	,	2	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Vaffelomelett_med_bacon.jpg'	),
(	131	,	'ENCHILADAS MED CHILIMARINERT KYLLING'	,	'https://trinesmatblogg.no/recipe/enchiladas-med-chilimarinert-kylling-pico-de-gallo/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/ENCHILADAS_MED_CHILIMARINERT_KYLLING_.jpg'	),
(	132	,	'Muslibar'	,	'http://www.lindastuhaug.no/2017/01/19/muslibar-med-notter/'	,	8	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Muslibar.jpg'	),
(	133	,	'Muslibar Trine'	,	'https://trinesmatblogg.no/recipe/muslibar-ut-pa-tur/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Muslibar_Trine.jpg'	),
(	134	,	'laks bibimbap'	,	''	,	2	,	'koreansk'	,	''	),
(	135	,	'Thaisalat med chilistekt kylling'	,	'https://www.nrk.no/mat/thaisalat-med-chilistekt-kylling-1.7457270'	,	4	,	'Thai, spicy'	,	'https://middagsappbilder.blob.core.windows.net/middag/Thaisalat_med_chilistekt_kylling.no/DcMWNl35GOBr7hRzy3q_wgwQRIhJqVCecLY67iUTjb1g'	),
(	136	,	'FRANSK LØKSUPPE'	,	'https://trinesmatblogg.no/recipe/fransk-loksuppe/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/FRANSK_LØKSUPPE.jpg'	),
(	137	,	'PASTAGRATENG MED KJØTTDEIG OG MOZZARELLA'	,	'https://trinesmatblogg.no/recipe/pastagrateng-med-kjottdeig-og-mozzarella/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/PASTAGRATENG_MED_KJØTTDEIG_OG_MOZZARELLA.jpg'	),
(	138	,	'Kimchi'	,	'http://www.justanotherfoodstory.com/koreansk-kimchi-pa-en-enkel-mate/'	,	4	,	'koreansk'	,	''	),
(	139	,	'Squashgetti carbonara'	,	'http://www.lindastuhaug.no/2015/09/08/squashgetti-carbonara/'	,	2	,	'LInda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Squashgetti_carbonara.jpg'	),
(	140	,	'Squashgetti carbonara med kylling'	,	'http://www.lindastuhaug.no/2016/02/23/squashgetti-carbonara-med-kylling/'	,	2	,	'LInda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Squashgetti_carbonara_med_kylling.jpg'	),
(	141	,	'Hjortegryte med kantarell og blomkålris'	,	'http://www.lindastuhaug.no/2015/11/18/hjortegryte-med-kantarell-og-blomkalris/'	,	4	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Hjortegryte_med_kantarell_og_blomkålris.jpg'	),
(	142	,	'Salsa'	,	'https://trinesmatblogg.no/2010/08/salsa/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Salsa.jpg'	),
(	143	,	'Guacamole'	,	''	,	2	,	'taco'	,	''	),
(	144	,	'SOYAMARINERT LAKS MED AGURK- OG EPLESALAT'	,	'https://trinesmatblogg.no/recipe/soyamarinert-laks-med-agurk-og-eplesalat/'	,	4	,	'fisk, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/SOYAMARINERT_LAKS_MED_AGURK-_OG_EPLESALAT.jpg'	),
(	145	,	'Mexican red rice'	,	'https://www.realsimple.com/food-recipes/browse-all-recipes/red-rice-recipe'	,	4	,	'taco'	,	'https://middagsappbilder.blob.core.windows.net/middag/Mexican_red_rice.jpg'	),
(	146	,	'POTET- OG EPLESALAT'	,	'https://trinesmatblogg.no/recipe/tind-speket-lammelar-med-potet-og-eplesalat/'	,	4	,	'Trine, tapas'	,	'https://middagsappbilder.blob.core.windows.net/middag/POTET-_OG_EPLESALAT.jpg'	),
(	147	,	'Dynket appelsinkake'	,	'https://www.detsoteliv.no/oppskrift/dynket-appelsinkake'	,	4	,	'kake, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Dynket_appelsinkake.jpg'	),
(	148	,	'Saftig og godt bananbrød'	,	'http://www.lindastuhaug.no/2016/11/04/saftig-godt-bananbrod/'	,	4	,	'kake, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Saftig_og_godt_bananbrød.jpg'	),
(	149	,	'Krema laks- og pastagrateng'	,	'http://www.lindastuhaug.no/2018/03/13/krema-laks-og-pastagrateng/'	,	4	,	'Linda, fisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Krema_laks-_og_pastagrateng.jpg'	),
(	150	,	'Chili con carne'	,	'https://trinesmatblogg.no/recipe/chili-con-carne-med-mork-sjokolade-og-hjemmelagde-tortillachips/'	,	6	,	'Trine, spicy'	,	'https://middagsappbilder.blob.core.windows.net/middag/Chili_con_carne.jpg'	),
(	151	,	'Olive salad'	,	''	,	2	,	'sommersalat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Olive_salad.jpg'	),
(	152	,	'Mediterranean sardine salad'	,	'https://www.bbcgoodfood.com/recipes/1648653/mediterranean-sardine-salad'	,	2	,	'salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Mediterranean_sardine_salad.jpg'	),
(	153	,	'Salmon and Avocado Caesar Salad'	,	'https://cafedelites.com/salmon-and-avocado-caesar-salad-recipe/'	,	2	,	'fisk, salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Salmon_and_Avocado_Caesar_Salad.jpg'	),
(	154	,	'grilled chili lime chicken fajita salad'	,	'https://cafedelites.com/grilled-chilli-lime-chicken-fajita-salad/'	,	4	,	'salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/grilled_chili_lime_chicken_fajita_salad.jpg'	),
(	155	,	'Thai Chicken Meatball Salad'	,	'https://www.bestrecipes.com.au/recipe/thai-chicken-meatball-salad-L19668.html'	,	2	,	'salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Thai_Chicken_Meatball_Salad.jpg'	),
(	156	,	'Egg & Puy lentil salad with tamari & watercress'	,	'https://www.bbcgoodfood.com/recipes/egg-puy-lentil-salad-tamari-watercress'	,	2	,	'salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Egg_&_Puy_lentil_salad_with_tamari_&_watercress.jpg'	),
(	157	,	'KYLLING CACCIATORA'	,	'https://trinesmatblogg.no/recipe/kylling-cacciatora/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/KYLLING_CACCIATORA.jpg'	),
(	158	,	'Glutenfri nøttebunn med sjokoladekrem'	,	'http://smakavhimmel.no/2015/07/glutenfri-nottebunn-med-kokosblomstsukker-en-allsidig-kakebunn-med-uendelige-muligheter/'	,	6	,	'Kake, dessert, glutenfri'	,	'https://middagsappbilder.blob.core.windows.net/middag/Glutenfri_nøttebunn_med_sjokoladekrem.jpg'	),
(	159	,	'PASTA CARBONARA uten fløte'	,	'https://norskmatglad.wordpress.com/spaghetti-carbonara-uten-flote/'	,	4	,	'laktosefri'	,	'https://middagsappbilder.blob.core.windows.net/middag/PASTA_CARBONARA_uten_fløte.jpg'	),
(	160	,	'GROVT MATPAKKEBRYTEBRØD'	,	'https://trinesmatblogg.no/recipe/grovt-matpakkebrytebrod/'	,	4	,	'bakst'	,	'https://middagsappbilder.blob.core.windows.net/middag/GROVT_MATPAKKEBRYTEBRØD.jpg'	),
(	161	,	'GROVE FROKOSTRUNDSTYKKER MED SOLSIKKEFRØ'	,	'https://trinesmatblogg.no/recipe/grove-frokostrundstykker-med-solsikkefro/'	,	4	,	'bakst'	,	'https://middagsappbilder.blob.core.windows.net/middag/GROVE_FROKOSTRUNDSTYKKER_MED_SOLSIKKEFRØ.jpg'	),
(	162	,	'Tomatsuppe med salsiccia, pasta og mozarella'	,	'https://trinesmatblogg.no/recipe/tomatsuppe-med-salsiccia-pasta-og-mozzarella/'	,	3	,	'Suppe, italiensk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tomatsuppe_med_salsiccia,_pasta_og_mozarella.jpg'	),
(	163	,	'Bibimbap'	,	'http://hls3790.tistory.com/356'	,	4	,	'korenask'	,	'https://middagsappbilder.blob.core.windows.net/middag/Bibimbap.jpg'	),
(	164	,	'Sukkerfri mandelkake med sjokoladefyll'	,	'http://www.lindastuhaug.no/2016/10/13/sukkerfri-mandelkake-sjokoladefyll/'	,	4	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Sukkerfri_mandelkake_med_sjokoladefyll.jpg'	),
(	165	,	'Lapskaus'	,	'https://meny.no/oppskrifter/Biff/Verdens-beste-lapskaus/'	,	8	,	'norsk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Lapskaus.jpg'	),
(	166	,	'Suksesskake'	,	'https://www.detsoteliv.no/oppskrift/suksesskake'	,	4	,	'kake, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Suksesskake.jpg'	),
(	167	,	'Fisketaco'	,	'https://meny.no/oppskrifter/Fisk/Torsk/Fredagstaco-med-torsk/'	,	2	,	'fisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/Fisketaco.jpg'	),
(	168	,	'KREMET PASTA MED LAKS OG ASPARGES'	,	'https://trinesmatblogg.no/recipe/kremet-pasta-med-laks-og-asparges-2/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/KREMET_PASTA_MED_LAKS_OG_ASPARGES.jpg'	),
(	169	,	'Nachos'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/kjott/nachos-med-enkel-guacamole'	,	4	,	'tine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Nachos.jpg'	),
(	170	,	'TACOSALAT'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/kjott/tacosalat'	,	4	,	'meksikansk'	,	'https://middagsappbilder.blob.core.windows.net/middag/TACOSALAT.jpg'	),
(	171	,	'GAZPACHO'	,	'https://trinesmatblogg.no/recipe/gazpacho/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/GAZPACHO.jpg'	),
(	172	,	'LAKS MED SPRØ GRØNNSAKER, RISNUDLER OG CHILISAUS'	,	'https://trinesmatblogg.no/recipe/laks-med-spro-gronnsaker-risnudler-og-chilisaus/'	,	4	,	'Trine, fisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/LAKS_MED_SPRØ_GRØNNSAKER,_RISNUDLER_OG_CHILISAUS.jpg'	),
(	173	,	'LAKS MED SPRØ GRØNNSAKER'	,	'https://trinesmatblogg.no/recipe/laks-med-spro-gronnsaker-risnudler-og-chilisaus/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/LAKS_MED_SPRØ_GRØNNSAKER.jpg'	),
(	174	,	'Kyllingsalat med pasta & pesto'	,	'http://www.lindastuhaug.no/2018/10/30/kyllingsalat-med-pasta-pesto/'	,	2	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kyllingsalat_med_pasta_&_pesto.jpg'	),
(	175	,	'Middagsomelett med potet og avokdo'	,	'http://www.lindastuhaug.no/2018/10/15/middagsomelett-med-potet-avokdo/'	,	4	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Middagsomelett_med_potet_og_avokdo.jpg'	),
(	176	,	'Eggemuffins'	,	'https://www.lindastuhaug.no/2014/04/06/supert-og-sunt-lunsjtips-eggemuffins/'	,	4	,	'Linda, lunsj'	,	'https://middagsappbilder.blob.core.windows.net/middag/Eggemuffins.jpg'	),
(	177	,	'pizza'	,	''	,	4	,	'Trine'	,	''	),
(	178	,	'speltscones'	,	'https://www.lindastuhaug.no/2018/11/07/saftige-speltscones-med-havre/'	,	4	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/speltscones.jpg'	),
(	179	,	'Enkel, krema pastasalat'	,	'https://www.lindastuhaug.no/2018/07/05/enkel-krema-pastasalat/'	,	2	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Enkel,_krema_pastasalat.jpg'	),
(	180	,	'SUPERRASK FISKEBURGER'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/fisk-og-skalldyr/superrask-fiskeburger'	,	4	,	'Fisk'	,	'https://middagsappbilder.blob.core.windows.net/middag/SUPERRASK_FISKEBURGER.jpg'	),
(	181	,	'GRESK KYLLING'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/kylling-og-fjarkre/gresk-kylling'	,	4	,	'Gresk'	,	'https://middagsappbilder.blob.core.windows.net/middag/GRESK_KYLLING.jpg'	),
(	182	,	'Gratinerte spicy lammeboller'	,	'https://www.nrk.no/mat/gratinerte-spicy-lammeboller-1.11938876'	,	4	,	'Lam, digg'	,	'https://middagsappbilder.blob.core.windows.net/middag/Gratinerte_spicy_lammeboller.no/q9_GUYL6MQD5JwSezKyY-ww5Lsg1nZ252swelLOcUAmw'	),
(	191	,	'Tomat- og gulrotsuppe med appelsin og chili'	,	'https://trinesmatblogg.no/recipe/ny-video-spicy-tomatsuppe-og-krutonger/'	,	4	,	'Suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tomat-_og_gulrotsuppe_med_appelsin_og_chili.jpg'	),
(	192	,	'Nøttekake med sjokolade og kaffekrem'	,	'https://www.nrk.no/mat/nottekake-med-sjokolade-og-kaffekrem-1.7480099'	,	10	,	'Dessert, glutenfri'	,	'https://gfx.nrk.no/yLGo-bIxW8gZuThxOgcOGApsu1Nca5Tje-SjM7-LIXVQ'	),
(	193	,	'Brokkolisalat'	,	'https://trinesmatblogg.no/recipe/brokkolisalat/'	,	4	,	'Salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Brokkolisalat.jpg'	),
(	195	,	'Grillet entrecôte med pære, gorgonzola'	,	'https://trinesmatblogg.no/recipe/grillet-entrecote-med-paere-gorgonzola-og-balsamico/'	,	4	,	'kjøtt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Grillet_entrecôte_med_pære,_gorgonzola.jpg'	),
(	196	,	'Kyllingsalat med spicy chilisaus'	,	'https://trinesmatblogg.no/recipe/kyllingsalat-med-spicy-chilisaus/'	,	3	,	'salat'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kyllingsalat_med_spicy_chilisaus.jpg'	),
(	197	,	'Snickerskake med krem og salt karamell'	,	'https://trinesmatblogg.no/recipe/snickerskake-med-krem-og-salt-karamell/'	,	6	,	'Kake, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Snickerskake_med_krem_og_salt_karamell.jpg'	),
(	198	,	'Asiatisk kylling taco'	,	'https://idagranjansen.com/oppskrifter/taco-med-asiatisk-marinert-kylling-avokado-og-romme'	,	2	,	'Taco, fredag, kos'	,	'https://middagsappbilder.blob.core.windows.net/middag/Asiatisk_kylling_taco.jpg'	),
(	199	,	'Pad thai med kylling'	,	'https://trinesmatblogg.no/recipe/pad-thai-med-kylling/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Pad_thai_med_kylling.jpg'	),
(	200	,	'Trine Moussaka'	,	'https://trinesmatblogg.no/2007/03/moussaka-med-gresk-salat/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Trine_Moussaka.jpg'	),
(	201	,	'BACONSURREDE KYLLINGLÅR & GRILLEDE TOMATER'	,	'https://trinesmatblogg.no/recipe/baconsurrede-kyllinglar-grillede-tomater/'	,	4	,	'Trine, grill'	,	'https://middagsappbilder.blob.core.windows.net/middag/BACONSURREDE_KYLLINGLÅR_&_GRILLEDE_TOMATER.jpg'	),
(	202	,	'Biffsalat'	,	'https://matpaabordet.no/2013/06/04/asiatisk-biffsalat-med-kal/'	,	4	,	'Asiatisk'	,	'http://matpaabordet.no/wp-content/uploads/blogger/-7J24tymrwH8/Ua4MNxmOreI/AAAAAAAAPMY/ejxBvEfNL4Q/s640/IMG_2843.JPG'	),
(	203	,	'Linsegryte med kylling og søtpote'	,	'https://sunnstart.no/linsegryte-med-kylling-og-sotpotet/'	,	1	,	'Sander'	,	'https://sunnstart.no/wp-content/uploads/2015/04/IMG_6507.jpg'	),
(	204	,	'Tigers Ville Gryte'	,	'https://sunnstart.no/tigers-ville-gryte/'	,	1	,	'Sander'	,	'https://sunnstart.no/wp-content/uploads/2015/01/img_63431.jpg'	),
(	205	,	'Kylling- og maisgryte'	,	'https://sunnstart.no/kylling-og-maisgryte/'	,	1	,	'Sander'	,	'https://sunnstart.no/wp-content/uploads/2015/04/IMG_6645-e1453206236382.jpg'	),
(	206	,	'Kikertpurè med brekkbønner og pære'	,	'https://sunnstart.no/kikertpure-brekkbonner-paere/'	,	1	,	'Sander'	,	'https://sunnstart.no/wp-content/uploads/2016/06/image-1024x1024.jpeg'	),
(	209	,	'Vafler'	,	'https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/verdens-beste-vafler'	,	4	,	'Dessert, kos'	,	'https://middagsappbilder.blob.core.windows.net/middag/Vafler.jpg'	),
(	210	,	'Søtpotetsuppe med bacon'	,	'https://www.melk.no/Oppskrifter/Supper/Supper-med-kjoett/Soetpotetsuppe-med-bacon-og-creme-fraiche'	,	6	,	'Suppe, enkelt'	,	'https://middagsappbilder.blob.core.windows.net/middag/Søtpotetsuppe_med_bacon_.gl/3sHGU1nTpahhtuz39'	),
(	211	,	'Italienske kjøttboller i tomatsaus'	,	'https://trinesmatblogg.no/recipe/italienske-kjottboller-i-tomatsaus/'	,	5	,	'Sander, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Italienske_kjøttboller_i_tomatsaus.jpg'	),
(	212	,	'Ostekake med gelé i flere lag'	,	'https://www.detsoteliv.no/oppskrift/ostekake-med-gele-i-flere-lag'	,	4	,	'Kake'	,	'https://middagsappbilder.blob.core.windows.net/middag/Ostekake_med_gelé_i_flere_lag.jpg'	),
(	213	,	'Ostekake med pistasj'	,	'https://trinesmatblogg.no/recipe/ostekake-med-pistasj-og-lime/'	,	4	,	'Kake, trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Ostekake_med_pistasj.jpg'	),
(	214	,	'PIZZASNURRER MED KJØTTSAUS'	,	'https://trinesmatblogg.no/recipe/pizzasnurrer-med-kjottsaus/'	,	4	,	'trine, Sander'	,	'https://middagsappbilder.blob.core.windows.net/middag/PIZZASNURRER_MED_KJØTTSAUS.jpg'	),
(	215	,	'Kylling med serranoskinke, brie, tomater og urter'	,	'https://trinesmatblogg.no/recipe/kylling-med-serranoskinke-brie-tomater-og-urter/'	,	4	,	'Kylling'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kylling_med_serranoskinke,_brie,_tomater_og_urter.jpg'	),
(	216	,	'Fiskebollesuppe'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/supper/fiskebollesuppe'	,	4	,	'Sander'	,	'https://middagsappbilder.blob.core.windows.net/middag/Fiskebollesuppe.jpg'	),
(	217	,	'Grønnsaksboller'	,	'https://www.nittedalernaering.no/2015/06/14/gronnsaksboller-med-linser-og-havre/'	,	4	,	'Sander'	,	'https://middagsappbilder.blob.core.windows.net/middag/Grønnsaksboller.jpg'	),
(	218	,	'Tilbehør til kjøttboller og grønnsaksboller'	,	'https://trinesmatblogg.no/recipe/kjottboller-med-sitronsaus-og-couscous/'	,	4	,	'Sander'	,	'https://middagsappbilder.blob.core.windows.net/middag/Tilbehør_til_kjøttboller_og_grønnsaksboller.jpg'	),
(	219	,	'Lasagne til mafiaen'	,	'https://trinesmatblogg.no/recipe/lasagne-til-mafiaen/'	,	8	,	''	,	'https://middagsappbilder.blob.core.windows.net/middag/Lasagne_til_mafiaen.jpg'	),
(	220	,	'Snickerskake i langpanne'	,	'https://www.detsoteliv.no/oppskrift/snickerskake-i-langpanne-med-mork-sjokoladeglasur'	,	6	,	'detsøteliv'	,	'https://middagsappbilder.blob.core.windows.net/middag/Snickerskake_i_langpanne.jpg'	),
(	221	,	'Kylling med chorizo, chili og cherrytomater'	,	'https://trinesmatblogg.no/recipe/kyllingform-med-chorizo-chili-og-cherrytomater/'	,	4	,	'Spicy'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kylling_med_chorizo,_chili_og_cherrytomater.jpg'	),
(	222	,	'Trippelkremkake'	,	'https://www.detsoteliv.no/oppskrift/trippelkremkake'	,	4	,	'detsoteliv, kake'	,	'https://middagsappbilder.blob.core.windows.net/middag/Trippelkremkake.jpg'	),
(	223	,	'Ostekake med friske jordbær'	,	'https://www.detsoteliv.no/oppskrift/ostekake-med-friske-jordbaer'	,	4	,	'kake'	,	'https://middagsappbilder.blob.core.windows.net/middag/Ostekake_med_friske_jordbær.jpg'	),
(	224	,	'Chorizogryte med linser og kikerter'	,	'https://trinesmatblogg.no/recipe/chorizogryte-med-linser-og-kikerter/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Chorizogryte_med_linser_og_kikerter.jpg'	),
(	225	,	'glutenfri hoisin saus'	,	'https://riktigkost.no/2017/03/28/hoisinsaus/'	,	1	,	'1'	,	'https://middagsappbilder.blob.core.windows.net/middag/glutenfri_hoisin_saus.jpg'	),
(	226	,	'Key lime pie'	,	'https://trinesmatblogg.no/recipe/key-lime-pie/'	,	6	,	'Kake, dessert'	,	'https://middagsappbilder.blob.core.windows.net/middag/Key_lime_pie_.jpg'	),
(	227	,	'Fiskesuppe'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/supper/fiskesuppe'	,	4	,	'Sander'	,	'https://middagsappbilder.blob.core.windows.net/middag/Fiskesuppe.jpg'	),
(	228	,	'Rødbetsuppe'	,	'https://www.tine.no/_/recipeimage/w_1920%2Ch_1080%2Cc_fill%2Cx_1500%2Cy_1000%2Cg_xy_center/recipeimage/320470.jpg'	,	4	,	'suppe'	,	'https://middagsappbilder.blob.core.windows.net/middag/Rødbetsuppe.no/oppskrifter/middag-og-hovedretter/supper/r%25C3%25B8dbetesuppe-med-matyoghurt'	),
(	229	,	'Kremet one pot-pasta med kylling, spinat og squash'	,	'https://trinesmatblogg.no/recipe/kremet-one-pot-pasta-med-kylling-spinat-og-squash/'	,	4	,	'trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kremet_one_pot-pasta_med_kylling,_spinat_og_squash.jpg'	),
(	230	,	'Laks med kimchi'	,	'https://photos.google.com/u/0/album/AF1QipO5Gcd1pnOvL1YiGpHs8XE1XhzLejwXqpQbGj73/photo/AF1QipMDpRIZVqhCNkma3e-5UzSKX7S59V7_BD9_RkOk'	,	4	,	'Godlevert'	,	''	),
(	231	,	'TORSKEFORM MED PAPRIKA & CHILISAUS'	,	'https://trinesmatblogg.no/recipe/torskeform-med-paprika-chilisaus/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/TORSKEFORM_MED_PAPRIKA_&_CHILISAUS.jpg'	),
(	232	,	'Quinoasalat med søtpotet'	,	'https://www.lindastuhaug.no/2018/05/14/quinoasalat-med-sotpotet-mango-og-fetaost/'	,	4	,	'linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Quinoasalat_med_søtpotet.jpg'	),
(	233	,	'Quesadillas med kikerter'	,	'https://photos.google.com/u/0/album/AF1QipO5Gcd1pnOvL1YiGpHs8XE1XhzLejwXqpQbGj73/photo/AF1QipOK8HKt__b1hLVyorw2N0SQHLDTjJrC6Qqwp2PG'	,	4	,	'godlevert'	,	''	),
(	234	,	'Laksepanne'	,	'https://www.lindastuhaug.no/2016/09/13/laksepanne-krema-parmesansaus/'	,	3	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Laksepanne.jpg'	),
(	235	,	'Laksepanne2'	,	'https://www.lindastuhaug.no/2016/09/13/laksepanne-krema-parmesansaus/'	,	3	,	'Linda'	,	'https://middagsappbilder.blob.core.windows.net/middag/Laksepanne2.jpg'	),
(	236	,	'Ovnsbakt torsk'	,	'https://www.tine.no/oppskrifter/middag-og-hovedretter/fisk-og-skalldyr/ovnsbakt-torsk'	,	4	,	'Tine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Ovnsbakt_torsk.jpg'	),
(	237	,	'Ovnsbakte kyllinglår med rotgrønnsaker og tomater'	,	'https://meny.no/oppskrifter/Kylling/Kyllinglar/Ovnsbakte-kyllinglar-med-rotgronnsaker-og-tomater/'	,	4	,	'Meny'	,	''	),
(	238	,	'Kebab'	,	'https://meny.no/oppskrifter/Lam/kebab-i-pita/'	,	4	,	'Meny'	,	''	),
(	239	,	'Lammefrikasse'	,	'https://meny.no/oppskrifter/gryte/Klassisk-lammefrikasse/'	,	4	,	'Meny'	,	''	),
(	240	,	'Lammefrikasse2'	,	'https://meny.no/oppskrifter/gryte/Klassisk-lammefrikasse/'	,	4	,	'Meny'	,	''	),
(	241	,	'Nakkekoteletter i form'	,	'https://meny.no/oppskrifter/Svin/Koteletter/Nakkekoteletter-i-form/'	,	4	,	'Meny'	,	'https://middagsappbilder.blob.core.windows.net/middag/Nakkekoteletter_i_form.jpg'	),
(	242	,	'Italiensk kyllinggryte'	,	'https://meny.no/oppskrifter/gryte/Italiensk-kyllinggryte/'	,	4	,	'Meny'	,	'https://middagsappbilder.blob.core.windows.net/middag/Italiensk_kyllinggryte.jpg'	),
(	244	,	'Kremet jordskokksuppe'	,	'https://meny.no/oppskrifter/Supper/Jordskokksuppe-med-bacon/'	,	4	,	'Meny'	,	''	),
(	245	,	'Gratinert kylling med paprika, spinat og parmesan'	,	'https://trinesmatblogg.no/recipe/gratinert-kylling-med-paprika-spinat-og-parmesan/'	,	4	,	'Kylling, middag'	,	'https://middagsappbilder.blob.core.windows.net/middag/Gratinert_kylling_med_paprika,_spinat_og_parmesan.jpg'	),
(	246	,	'Kyllingpai med spinat, tomat og feta'	,	'https://trinesmatblogg.no/recipe/kyllingpai-med-spinat-tomat-og-feta/'	,	4	,	'Trine'	,	'https://middagsappbilder.blob.core.windows.net/middag/Kyllingpai_med_spinat,_tomat_og_feta.jpg'	),
(	247	,	'Linsesuppe'	,	'https://meny.no/oppskrifter/Supper/Superrask-linsesuppe/'	,	4	,	'Meny'	,	''	),
(	248	,	'Avokado carbonara'	,	'https://gladkokken.no/oppskrifter/avokado-carbonara-bacon-munkholm'	,	2	,	'Middag, enkel'	,	''	),
(	249	,	'Tortilla omelett'	,	'https://gladkokken.no/oppskrifter/tortilla-omelett-superenkel-og-god-middag-laget-pa-fa-minutter'	,	2	,	'Enkel'	,	''	)
